# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dv < Formula
  desc "A command line tool to remove AWS default VPC(s)"
  homepage "https://github.com/knakayama/dv"
  version "9.9.9"
  license "MIT"

  depends_on "go" => :optional

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/knakayama/dv/releases/download/v9.9.9/dv_9.9.9_Darwin_x86_64.tar.gz"
      sha256 "0aacb9ceead336200d2aede8b467356fc3128c5a02be0d28667079578413a16c"

      def install
        bin.install "dv"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/knakayama/dv/releases/download/v9.9.9/dv_9.9.9_Darwin_arm64.tar.gz"
      sha256 "976604b59c404bb2da3b46b3d01b5a6c53865d79be306a37905338b1eb6002c7"

      def install
        bin.install "dv"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/knakayama/dv/releases/download/v9.9.9/dv_9.9.9_Linux_arm64.tar.gz"
      sha256 "af32057972dcf3d67861f3a834a569465aa446d93f54936d8b5eddf4ea9425e6"

      def install
        bin.install "dv"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/knakayama/dv/releases/download/v9.9.9/dv_9.9.9_Linux_x86_64.tar.gz"
      sha256 "403710f8b75be3d2c70c561cda4cd618dfb3a92ea5f0dedce4cef1e2d7fb51e8"

      def install
        bin.install "dv"
      end
    end
  end

  test do
    system "#{bin}/dv -v"
  end
end
